# Generated by Django 6.0.1 on 2026-04-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasalItems',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=90)),
                ('images', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('rating', models.FloatField()),
                ('category', models.CharField(choices=[('oil', 'Oil'), ('masala', 'Masala'), ('powderdspice', 'PowderSpice'), ('saltsugar', 'SaltSugar')], max_length=50)),
            ],
        ),
    ]
