# Generated by Django 6.0.1 on 2026-04-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masalitems',
            name='category',
            field=models.CharField(choices=[('oil', 'Oil'), ('masala', 'Masala'), ('desighee', 'DesiGhee'), ('saltsugar', 'SaltSugar')], max_length=50),
        ),
    ]
